// SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ViewLayout } from "./utils/breakpoints";
import { IconName } from "./blocks/icon/icon.component";
import { Map, MapGeoJSONFeature, RequestTransformFunction } from "maplibre-gl";
import { LayerConfig } from "./blocks/map-layer-base-odh/noi-map-layer-base-odh.component";
import { PopupDefinitionFn } from "./utils/maplibre-popup";
import { ZoomCategory } from "./blocks/otp/map-layer-otp-layers/layout";
import { OtpStation, OtpStop, OtpStoptime, OtpTrip } from "./data/noi/Otp";
import { WeatherCurrentViewMode } from "./blocks/map-layer-weather-current/noi-map-layer-weather-current.component";
import { WeatherForecast } from "./data/noi/WeatherForecase";
import { SelectOption } from "./blocks/select/select.component";
export { ViewLayout } from "./utils/breakpoints";
export { IconName } from "./blocks/icon/icon.component";
export { Map, MapGeoJSONFeature, RequestTransformFunction } from "maplibre-gl";
export { LayerConfig } from "./blocks/map-layer-base-odh/noi-map-layer-base-odh.component";
export { PopupDefinitionFn } from "./utils/maplibre-popup";
export { ZoomCategory } from "./blocks/otp/map-layer-otp-layers/layout";
export { OtpStation, OtpStop, OtpStoptime, OtpTrip } from "./data/noi/Otp";
export { WeatherCurrentViewMode } from "./blocks/map-layer-weather-current/noi-map-layer-weather-current.component";
export { WeatherForecast } from "./data/noi/WeatherForecase";
export { SelectOption } from "./blocks/select/select.component";
export namespace Components {
    /**
     * (INTERNAL) render a badge.
     */
    interface NoiBadge {
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface NoiButton {
        /**
          * button 'disabled' property
          * @default false
         */
        "disabled": boolean;
        /**
          * icon-only buttons has circle shape. The size of the button can be changed with "font-size" style
          * @default false
         */
        "iconOnly": boolean;
    }
    /**
     * (INTERNAL) render a checkbox
     */
    interface NoiCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * 'disabled' property
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "kind": 'checkbox' | 'chevron';
        /**
          * @default false
         */
        "loading": boolean;
    }
    /**
     * (INTERNAL) render a checkbox group
     */
    interface NoiCheckboxGroup {
        /**
          * @default false
         */
        "open": boolean;
    }
    /**
     * Consolidated web-component to show Open Data Hub data imported within the Digiway project
     */
    interface NoiDigiway {
        /**
          * Base map layer
          * @default 'tirol'
         */
        "baseMap": 'osm' | 'tirol';
        /**
          * Pass latitude, longitude and zoomlevel separated by "," if map should be centered an a specific gps point
         */
        "centermap"?: string;
        /**
          * Language
          * @default 'en'
         */
        "language": string;
        /**
          * Layout appearance
          * @default 'auto'
         */
        "layout": ViewLayout;
        /**
          * View date for weather data (weather layer only)
         */
        "viewDate": string | undefined;
    }
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiIcon {
        /**
          * icon name
         */
        "name"?: IconName | string;
    }
    /**
     * (INTERNAL) render a basic map with no layouts
     */
    interface NoiMap {
        /**
          * Map center. Pass latitude, longitude and zoomlevel separated by "," if map should be centered an a specific gps point
         */
        "centermap"?: string;
        "getMapAsync": () => Promise<Map>;
        "setUrlTransform": (urlPart: string, transformFn: RequestTransformFunction | null) => Promise<void>;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapBaseCarto {
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapBaseOsm {
        /**
          * @default 'color'
         */
        "variant": 'color' | 'grayscale';
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapBaseTirol {
        /**
          * @default 'color'
         */
        "variant": 'color' | 'grayscale';
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerAnnouncements {
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerBaseOdh {
        "config": LayerConfig;
        "popupStructure"?: PopupDefinitionFn;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtp {
        "layers"?: string | string[];
        "layout"?: ViewLayout;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtpCharger {
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtpIcons {
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtpParking {
    }
    /**
     * (INTERNAL) render otp popup
     */
    interface NoiMapLayerOtpPopupParking {
        "setData": (stopInfo: MapGeoJSONFeature) => Promise<void>;
    }
    /**
     * (INTERNAL) render otp popup
     */
    interface NoiMapLayerOtpPopupStop {
        "setData": (stopInfo: OtpStop | OtpStation, vehicleMode?: string) => Promise<void>;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtpRental {
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtpSource {
        "isDestroying": () => Promise<boolean>;
        "waitSourceReady": () => Promise<void>;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtpStops {
    }
    /**
     * (INTERNAL)
     */
    interface NoiMapLayerOtpTrip {
        "layout"?: ViewLayout;
        /**
          * Optional
         */
        "stopId"?: string;
        /**
          * Required
         */
        "tripId"?: string;
        "vehicleTypeOverride"?: string;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerPoi {
        /**
          * View date for weather data
         */
        "tag"?: string;
    }
    /**
     * (INTERNAL) render map popup
     */
    interface NoiMapLayerPoiAccommodationPopup {
        "setFeatureId": (featureId: string) => Promise<void>;
        "setName": (featureName: string) => Promise<void>;
    }
    /**
     * (INTERNAL) render map popup
     */
    interface NoiMapLayerPoiPopup {
        "setFeatureId": (featureId: string) => Promise<void>;
        "setName": (featureName: string) => Promise<void>;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerRiskExposure {
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerRoads {
        "region": 'tyrol'
    | 'tyrol-north'
    | 'bolzano-int'
    | 'trento'
    | 'mountain-bike-bolzano'
    | 'mountain-bike-trento'
    | 'hiking-bolzano'
    | 'hiking-trento'
    | 'hiking-e5'
    | 'hiking-accessible';
        "titleIcon"?: string;
        "titleText"?: string;
    }
    /**
     * (INTERNAL) render map popup
     */
    interface NoiMapLayerRoadsPopup {
        "setName": (geoName: string) => Promise<void>;
        "setPointId": (roadId: string) => Promise<void>;
        "setPopupHeader": (headerConfig: HeaderConfig) => Promise<void>;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerWeather {
        /**
          * View date for weather data
         */
        "viewDate": Date | undefined;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerWeatherCurrent {
        "reloadData": () => Promise<void>;
        /**
          * View date for weather data
          * @default 'temperature'
         */
        "viewMode": WeatherCurrentViewMode;
    }
    /**
     * (INTERNAL) render map popup
     */
    interface NoiMapLayerWeatherPopup {
        "setFeature": (feature: MapGeoJSONFeature) => Promise<void>;
    }
    interface NoiOtpDepartureTime {
        /**
          * @default true
         */
        "showDelay": boolean;
        "stoptime"?: OtpStoptime;
    }
    /**
     * (INTERNAL) render a select box
     */
    interface NoiSelect {
        /**
          * button 'disabled' property
          * @default false
         */
        "disabled": boolean;
        "options": SelectOption[];
        /**
          * @default null
         */
        "value": string;
    }
    /**
     * (INTERNAL) render a apinner.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiSpinner {
    }
    /**
     * (INTERNAL) render stars.
     */
    interface NoiStars {
        /**
          * @default 0
         */
        "stars": number;
        /**
          * @default 5
         */
        "total": number;
    }
}
export interface NoiButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiButtonElement;
}
export interface NoiCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiCheckboxElement;
}
export interface NoiMapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapElement;
}
export interface NoiMapLayerAnnouncementsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerAnnouncementsElement;
}
export interface NoiMapLayerBaseOdhCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerBaseOdhElement;
}
export interface NoiMapLayerOtpCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerOtpElement;
}
export interface NoiMapLayerOtpChargerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerOtpChargerElement;
}
export interface NoiMapLayerOtpParkingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerOtpParkingElement;
}
export interface NoiMapLayerOtpPopupParkingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerOtpPopupParkingElement;
}
export interface NoiMapLayerOtpPopupStopCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerOtpPopupStopElement;
}
export interface NoiMapLayerOtpRentalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerOtpRentalElement;
}
export interface NoiMapLayerOtpSourceCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerOtpSourceElement;
}
export interface NoiMapLayerOtpStopsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerOtpStopsElement;
}
export interface NoiMapLayerOtpTripCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerOtpTripElement;
}
export interface NoiMapLayerPoiCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerPoiElement;
}
export interface NoiMapLayerRiskExposureCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerRiskExposureElement;
}
export interface NoiMapLayerRoadsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerRoadsElement;
}
export interface NoiMapLayerWeatherCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerWeatherElement;
}
export interface NoiMapLayerWeatherCurrentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapLayerWeatherCurrentElement;
}
export interface NoiSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiSelectElement;
}
declare global {
    /**
     * (INTERNAL) render a badge.
     */
    interface HTMLNoiBadgeElement extends Components.NoiBadge, HTMLStencilElement {
    }
    var HTMLNoiBadgeElement: {
        prototype: HTMLNoiBadgeElement;
        new (): HTMLNoiBadgeElement;
    };
    interface HTMLNoiButtonElementEventMap {
        "btnClick": MouseEvent;
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface HTMLNoiButtonElement extends Components.NoiButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiButtonElementEventMap>(type: K, listener: (this: HTMLNoiButtonElement, ev: NoiButtonCustomEvent<HTMLNoiButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiButtonElementEventMap>(type: K, listener: (this: HTMLNoiButtonElement, ev: NoiButtonCustomEvent<HTMLNoiButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiButtonElement: {
        prototype: HTMLNoiButtonElement;
        new (): HTMLNoiButtonElement;
    };
    interface HTMLNoiCheckboxElementEventMap {
        "checkedChange": { checked: boolean };
    }
    /**
     * (INTERNAL) render a checkbox
     */
    interface HTMLNoiCheckboxElement extends Components.NoiCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiCheckboxElementEventMap>(type: K, listener: (this: HTMLNoiCheckboxElement, ev: NoiCheckboxCustomEvent<HTMLNoiCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiCheckboxElementEventMap>(type: K, listener: (this: HTMLNoiCheckboxElement, ev: NoiCheckboxCustomEvent<HTMLNoiCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiCheckboxElement: {
        prototype: HTMLNoiCheckboxElement;
        new (): HTMLNoiCheckboxElement;
    };
    /**
     * (INTERNAL) render a checkbox group
     */
    interface HTMLNoiCheckboxGroupElement extends Components.NoiCheckboxGroup, HTMLStencilElement {
    }
    var HTMLNoiCheckboxGroupElement: {
        prototype: HTMLNoiCheckboxGroupElement;
        new (): HTMLNoiCheckboxGroupElement;
    };
    /**
     * Consolidated web-component to show Open Data Hub data imported within the Digiway project
     */
    interface HTMLNoiDigiwayElement extends Components.NoiDigiway, HTMLStencilElement {
    }
    var HTMLNoiDigiwayElement: {
        prototype: HTMLNoiDigiwayElement;
        new (): HTMLNoiDigiwayElement;
    };
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface HTMLNoiIconElement extends Components.NoiIcon, HTMLStencilElement {
    }
    var HTMLNoiIconElement: {
        prototype: HTMLNoiIconElement;
        new (): HTMLNoiIconElement;
    };
    interface HTMLNoiMapElementEventMap {
        "mapReady": Map;
    }
    /**
     * (INTERNAL) render a basic map with no layouts
     */
    interface HTMLNoiMapElement extends Components.NoiMap, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapElementEventMap>(type: K, listener: (this: HTMLNoiMapElement, ev: NoiMapCustomEvent<HTMLNoiMapElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapElementEventMap>(type: K, listener: (this: HTMLNoiMapElement, ev: NoiMapCustomEvent<HTMLNoiMapElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapElement: {
        prototype: HTMLNoiMapElement;
        new (): HTMLNoiMapElement;
    };
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapBaseCartoElement extends Components.NoiMapBaseCarto, HTMLStencilElement {
    }
    var HTMLNoiMapBaseCartoElement: {
        prototype: HTMLNoiMapBaseCartoElement;
        new (): HTMLNoiMapBaseCartoElement;
    };
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapBaseOsmElement extends Components.NoiMapBaseOsm, HTMLStencilElement {
    }
    var HTMLNoiMapBaseOsmElement: {
        prototype: HTMLNoiMapBaseOsmElement;
        new (): HTMLNoiMapBaseOsmElement;
    };
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapBaseTirolElement extends Components.NoiMapBaseTirol, HTMLStencilElement {
    }
    var HTMLNoiMapBaseTirolElement: {
        prototype: HTMLNoiMapBaseTirolElement;
        new (): HTMLNoiMapBaseTirolElement;
    };
    interface HTMLNoiMapLayerAnnouncementsElementEventMap {
        "layerLoading": boolean;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerAnnouncementsElement extends Components.NoiMapLayerAnnouncements, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerAnnouncementsElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerAnnouncementsElement, ev: NoiMapLayerAnnouncementsCustomEvent<HTMLNoiMapLayerAnnouncementsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerAnnouncementsElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerAnnouncementsElement, ev: NoiMapLayerAnnouncementsCustomEvent<HTMLNoiMapLayerAnnouncementsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerAnnouncementsElement: {
        prototype: HTMLNoiMapLayerAnnouncementsElement;
        new (): HTMLNoiMapLayerAnnouncementsElement;
    };
    interface HTMLNoiMapLayerBaseOdhElementEventMap {
        "layerLoading": boolean;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerBaseOdhElement extends Components.NoiMapLayerBaseOdh, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerBaseOdhElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerBaseOdhElement, ev: NoiMapLayerBaseOdhCustomEvent<HTMLNoiMapLayerBaseOdhElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerBaseOdhElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerBaseOdhElement, ev: NoiMapLayerBaseOdhCustomEvent<HTMLNoiMapLayerBaseOdhElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerBaseOdhElement: {
        prototype: HTMLNoiMapLayerBaseOdhElement;
        new (): HTMLNoiMapLayerBaseOdhElement;
    };
    interface HTMLNoiMapLayerOtpElementEventMap {
        "layerLoading": boolean;
        "zoomCategoryChange": ZoomCategory;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerOtpElement extends Components.NoiMapLayerOtp, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerOtpElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpElement, ev: NoiMapLayerOtpCustomEvent<HTMLNoiMapLayerOtpElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerOtpElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpElement, ev: NoiMapLayerOtpCustomEvent<HTMLNoiMapLayerOtpElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerOtpElement: {
        prototype: HTMLNoiMapLayerOtpElement;
        new (): HTMLNoiMapLayerOtpElement;
    };
    interface HTMLNoiMapLayerOtpChargerElementEventMap {
        "layerLoading": boolean;
        "featureClick": MapGeoJSONFeature;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerOtpChargerElement extends Components.NoiMapLayerOtpCharger, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerOtpChargerElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpChargerElement, ev: NoiMapLayerOtpChargerCustomEvent<HTMLNoiMapLayerOtpChargerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerOtpChargerElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpChargerElement, ev: NoiMapLayerOtpChargerCustomEvent<HTMLNoiMapLayerOtpChargerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerOtpChargerElement: {
        prototype: HTMLNoiMapLayerOtpChargerElement;
        new (): HTMLNoiMapLayerOtpChargerElement;
    };
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerOtpIconsElement extends Components.NoiMapLayerOtpIcons, HTMLStencilElement {
    }
    var HTMLNoiMapLayerOtpIconsElement: {
        prototype: HTMLNoiMapLayerOtpIconsElement;
        new (): HTMLNoiMapLayerOtpIconsElement;
    };
    interface HTMLNoiMapLayerOtpParkingElementEventMap {
        "featureClick": MapGeoJSONFeature;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerOtpParkingElement extends Components.NoiMapLayerOtpParking, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerOtpParkingElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpParkingElement, ev: NoiMapLayerOtpParkingCustomEvent<HTMLNoiMapLayerOtpParkingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerOtpParkingElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpParkingElement, ev: NoiMapLayerOtpParkingCustomEvent<HTMLNoiMapLayerOtpParkingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerOtpParkingElement: {
        prototype: HTMLNoiMapLayerOtpParkingElement;
        new (): HTMLNoiMapLayerOtpParkingElement;
    };
    interface HTMLNoiMapLayerOtpPopupParkingElementEventMap {
        "routeClick": OtpTrip;
    }
    /**
     * (INTERNAL) render otp popup
     */
    interface HTMLNoiMapLayerOtpPopupParkingElement extends Components.NoiMapLayerOtpPopupParking, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerOtpPopupParkingElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpPopupParkingElement, ev: NoiMapLayerOtpPopupParkingCustomEvent<HTMLNoiMapLayerOtpPopupParkingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerOtpPopupParkingElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpPopupParkingElement, ev: NoiMapLayerOtpPopupParkingCustomEvent<HTMLNoiMapLayerOtpPopupParkingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerOtpPopupParkingElement: {
        prototype: HTMLNoiMapLayerOtpPopupParkingElement;
        new (): HTMLNoiMapLayerOtpPopupParkingElement;
    };
    interface HTMLNoiMapLayerOtpPopupStopElementEventMap {
        "routeClick": OtpStoptime;
    }
    /**
     * (INTERNAL) render otp popup
     */
    interface HTMLNoiMapLayerOtpPopupStopElement extends Components.NoiMapLayerOtpPopupStop, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerOtpPopupStopElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpPopupStopElement, ev: NoiMapLayerOtpPopupStopCustomEvent<HTMLNoiMapLayerOtpPopupStopElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerOtpPopupStopElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpPopupStopElement, ev: NoiMapLayerOtpPopupStopCustomEvent<HTMLNoiMapLayerOtpPopupStopElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerOtpPopupStopElement: {
        prototype: HTMLNoiMapLayerOtpPopupStopElement;
        new (): HTMLNoiMapLayerOtpPopupStopElement;
    };
    interface HTMLNoiMapLayerOtpRentalElementEventMap {
        "featureClick": MapGeoJSONFeature;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerOtpRentalElement extends Components.NoiMapLayerOtpRental, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerOtpRentalElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpRentalElement, ev: NoiMapLayerOtpRentalCustomEvent<HTMLNoiMapLayerOtpRentalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerOtpRentalElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpRentalElement, ev: NoiMapLayerOtpRentalCustomEvent<HTMLNoiMapLayerOtpRentalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerOtpRentalElement: {
        prototype: HTMLNoiMapLayerOtpRentalElement;
        new (): HTMLNoiMapLayerOtpRentalElement;
    };
    interface HTMLNoiMapLayerOtpSourceElementEventMap {
        "layerLoading": boolean;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerOtpSourceElement extends Components.NoiMapLayerOtpSource, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerOtpSourceElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpSourceElement, ev: NoiMapLayerOtpSourceCustomEvent<HTMLNoiMapLayerOtpSourceElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerOtpSourceElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpSourceElement, ev: NoiMapLayerOtpSourceCustomEvent<HTMLNoiMapLayerOtpSourceElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerOtpSourceElement: {
        prototype: HTMLNoiMapLayerOtpSourceElement;
        new (): HTMLNoiMapLayerOtpSourceElement;
    };
    interface HTMLNoiMapLayerOtpStopsElementEventMap {
        "featureClick": MapGeoJSONFeature;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerOtpStopsElement extends Components.NoiMapLayerOtpStops, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerOtpStopsElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpStopsElement, ev: NoiMapLayerOtpStopsCustomEvent<HTMLNoiMapLayerOtpStopsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerOtpStopsElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpStopsElement, ev: NoiMapLayerOtpStopsCustomEvent<HTMLNoiMapLayerOtpStopsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerOtpStopsElement: {
        prototype: HTMLNoiMapLayerOtpStopsElement;
        new (): HTMLNoiMapLayerOtpStopsElement;
    };
    interface HTMLNoiMapLayerOtpTripElementEventMap {
        "close": 'back' | 'close';
    }
    /**
     * (INTERNAL)
     */
    interface HTMLNoiMapLayerOtpTripElement extends Components.NoiMapLayerOtpTrip, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerOtpTripElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpTripElement, ev: NoiMapLayerOtpTripCustomEvent<HTMLNoiMapLayerOtpTripElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerOtpTripElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerOtpTripElement, ev: NoiMapLayerOtpTripCustomEvent<HTMLNoiMapLayerOtpTripElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerOtpTripElement: {
        prototype: HTMLNoiMapLayerOtpTripElement;
        new (): HTMLNoiMapLayerOtpTripElement;
    };
    interface HTMLNoiMapLayerPoiElementEventMap {
        "layerLoading": boolean;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerPoiElement extends Components.NoiMapLayerPoi, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerPoiElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerPoiElement, ev: NoiMapLayerPoiCustomEvent<HTMLNoiMapLayerPoiElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerPoiElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerPoiElement, ev: NoiMapLayerPoiCustomEvent<HTMLNoiMapLayerPoiElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerPoiElement: {
        prototype: HTMLNoiMapLayerPoiElement;
        new (): HTMLNoiMapLayerPoiElement;
    };
    /**
     * (INTERNAL) render map popup
     */
    interface HTMLNoiMapLayerPoiAccommodationPopupElement extends Components.NoiMapLayerPoiAccommodationPopup, HTMLStencilElement {
    }
    var HTMLNoiMapLayerPoiAccommodationPopupElement: {
        prototype: HTMLNoiMapLayerPoiAccommodationPopupElement;
        new (): HTMLNoiMapLayerPoiAccommodationPopupElement;
    };
    /**
     * (INTERNAL) render map popup
     */
    interface HTMLNoiMapLayerPoiPopupElement extends Components.NoiMapLayerPoiPopup, HTMLStencilElement {
    }
    var HTMLNoiMapLayerPoiPopupElement: {
        prototype: HTMLNoiMapLayerPoiPopupElement;
        new (): HTMLNoiMapLayerPoiPopupElement;
    };
    interface HTMLNoiMapLayerRiskExposureElementEventMap {
        "layerLoading": boolean;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerRiskExposureElement extends Components.NoiMapLayerRiskExposure, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerRiskExposureElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerRiskExposureElement, ev: NoiMapLayerRiskExposureCustomEvent<HTMLNoiMapLayerRiskExposureElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerRiskExposureElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerRiskExposureElement, ev: NoiMapLayerRiskExposureCustomEvent<HTMLNoiMapLayerRiskExposureElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerRiskExposureElement: {
        prototype: HTMLNoiMapLayerRiskExposureElement;
        new (): HTMLNoiMapLayerRiskExposureElement;
    };
    interface HTMLNoiMapLayerRoadsElementEventMap {
        "layerLoading": boolean;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerRoadsElement extends Components.NoiMapLayerRoads, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerRoadsElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerRoadsElement, ev: NoiMapLayerRoadsCustomEvent<HTMLNoiMapLayerRoadsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerRoadsElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerRoadsElement, ev: NoiMapLayerRoadsCustomEvent<HTMLNoiMapLayerRoadsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerRoadsElement: {
        prototype: HTMLNoiMapLayerRoadsElement;
        new (): HTMLNoiMapLayerRoadsElement;
    };
    /**
     * (INTERNAL) render map popup
     */
    interface HTMLNoiMapLayerRoadsPopupElement extends Components.NoiMapLayerRoadsPopup, HTMLStencilElement {
    }
    var HTMLNoiMapLayerRoadsPopupElement: {
        prototype: HTMLNoiMapLayerRoadsPopupElement;
        new (): HTMLNoiMapLayerRoadsPopupElement;
    };
    interface HTMLNoiMapLayerWeatherElementEventMap {
        "layerLoading": boolean;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerWeatherElement extends Components.NoiMapLayerWeather, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerWeatherElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerWeatherElement, ev: NoiMapLayerWeatherCustomEvent<HTMLNoiMapLayerWeatherElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerWeatherElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerWeatherElement, ev: NoiMapLayerWeatherCustomEvent<HTMLNoiMapLayerWeatherElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerWeatherElement: {
        prototype: HTMLNoiMapLayerWeatherElement;
        new (): HTMLNoiMapLayerWeatherElement;
    };
    interface HTMLNoiMapLayerWeatherCurrentElementEventMap {
        "layerLoading": boolean;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface HTMLNoiMapLayerWeatherCurrentElement extends Components.NoiMapLayerWeatherCurrent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapLayerWeatherCurrentElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerWeatherCurrentElement, ev: NoiMapLayerWeatherCurrentCustomEvent<HTMLNoiMapLayerWeatherCurrentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapLayerWeatherCurrentElementEventMap>(type: K, listener: (this: HTMLNoiMapLayerWeatherCurrentElement, ev: NoiMapLayerWeatherCurrentCustomEvent<HTMLNoiMapLayerWeatherCurrentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapLayerWeatherCurrentElement: {
        prototype: HTMLNoiMapLayerWeatherCurrentElement;
        new (): HTMLNoiMapLayerWeatherCurrentElement;
    };
    /**
     * (INTERNAL) render map popup
     */
    interface HTMLNoiMapLayerWeatherPopupElement extends Components.NoiMapLayerWeatherPopup, HTMLStencilElement {
    }
    var HTMLNoiMapLayerWeatherPopupElement: {
        prototype: HTMLNoiMapLayerWeatherPopupElement;
        new (): HTMLNoiMapLayerWeatherPopupElement;
    };
    interface HTMLNoiOtpDepartureTimeElement extends Components.NoiOtpDepartureTime, HTMLStencilElement {
    }
    var HTMLNoiOtpDepartureTimeElement: {
        prototype: HTMLNoiOtpDepartureTimeElement;
        new (): HTMLNoiOtpDepartureTimeElement;
    };
    interface HTMLNoiSelectElementEventMap {
        "selectChange": string;
    }
    /**
     * (INTERNAL) render a select box
     */
    interface HTMLNoiSelectElement extends Components.NoiSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiSelectElementEventMap>(type: K, listener: (this: HTMLNoiSelectElement, ev: NoiSelectCustomEvent<HTMLNoiSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiSelectElementEventMap>(type: K, listener: (this: HTMLNoiSelectElement, ev: NoiSelectCustomEvent<HTMLNoiSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiSelectElement: {
        prototype: HTMLNoiSelectElement;
        new (): HTMLNoiSelectElement;
    };
    /**
     * (INTERNAL) render a apinner.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface HTMLNoiSpinnerElement extends Components.NoiSpinner, HTMLStencilElement {
    }
    var HTMLNoiSpinnerElement: {
        prototype: HTMLNoiSpinnerElement;
        new (): HTMLNoiSpinnerElement;
    };
    /**
     * (INTERNAL) render stars.
     */
    interface HTMLNoiStarsElement extends Components.NoiStars, HTMLStencilElement {
    }
    var HTMLNoiStarsElement: {
        prototype: HTMLNoiStarsElement;
        new (): HTMLNoiStarsElement;
    };
    interface HTMLElementTagNameMap {
        "noi-badge": HTMLNoiBadgeElement;
        "noi-button": HTMLNoiButtonElement;
        "noi-checkbox": HTMLNoiCheckboxElement;
        "noi-checkbox-group": HTMLNoiCheckboxGroupElement;
        "noi-digiway": HTMLNoiDigiwayElement;
        "noi-icon": HTMLNoiIconElement;
        "noi-map": HTMLNoiMapElement;
        "noi-map-base-carto": HTMLNoiMapBaseCartoElement;
        "noi-map-base-osm": HTMLNoiMapBaseOsmElement;
        "noi-map-base-tirol": HTMLNoiMapBaseTirolElement;
        "noi-map-layer-announcements": HTMLNoiMapLayerAnnouncementsElement;
        "noi-map-layer-base-odh": HTMLNoiMapLayerBaseOdhElement;
        "noi-map-layer-otp": HTMLNoiMapLayerOtpElement;
        "noi-map-layer-otp-charger": HTMLNoiMapLayerOtpChargerElement;
        "noi-map-layer-otp-icons": HTMLNoiMapLayerOtpIconsElement;
        "noi-map-layer-otp-parking": HTMLNoiMapLayerOtpParkingElement;
        "noi-map-layer-otp-popup-parking": HTMLNoiMapLayerOtpPopupParkingElement;
        "noi-map-layer-otp-popup-stop": HTMLNoiMapLayerOtpPopupStopElement;
        "noi-map-layer-otp-rental": HTMLNoiMapLayerOtpRentalElement;
        "noi-map-layer-otp-source": HTMLNoiMapLayerOtpSourceElement;
        "noi-map-layer-otp-stops": HTMLNoiMapLayerOtpStopsElement;
        "noi-map-layer-otp-trip": HTMLNoiMapLayerOtpTripElement;
        "noi-map-layer-poi": HTMLNoiMapLayerPoiElement;
        "noi-map-layer-poi-accommodation-popup": HTMLNoiMapLayerPoiAccommodationPopupElement;
        "noi-map-layer-poi-popup": HTMLNoiMapLayerPoiPopupElement;
        "noi-map-layer-risk-exposure": HTMLNoiMapLayerRiskExposureElement;
        "noi-map-layer-roads": HTMLNoiMapLayerRoadsElement;
        "noi-map-layer-roads-popup": HTMLNoiMapLayerRoadsPopupElement;
        "noi-map-layer-weather": HTMLNoiMapLayerWeatherElement;
        "noi-map-layer-weather-current": HTMLNoiMapLayerWeatherCurrentElement;
        "noi-map-layer-weather-popup": HTMLNoiMapLayerWeatherPopupElement;
        "noi-otp-departure-time": HTMLNoiOtpDepartureTimeElement;
        "noi-select": HTMLNoiSelectElement;
        "noi-spinner": HTMLNoiSpinnerElement;
        "noi-stars": HTMLNoiStarsElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    /**
     * (INTERNAL) render a badge.
     */
    interface NoiBadge {
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface NoiButton {
        /**
          * button 'disabled' property
          * @default false
         */
        "disabled"?: boolean;
        /**
          * icon-only buttons has circle shape. The size of the button can be changed with "font-size" style
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * Emitted when user clicks on the button
         */
        "onBtnClick"?: (event: NoiButtonCustomEvent<MouseEvent>) => void;
    }
    /**
     * (INTERNAL) render a checkbox
     */
    interface NoiCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * 'disabled' property
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "kind"?: 'checkbox' | 'chevron';
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted when user clicks on the button
         */
        "onCheckedChange"?: (event: NoiCheckboxCustomEvent<{ checked: boolean }>) => void;
    }
    /**
     * (INTERNAL) render a checkbox group
     */
    interface NoiCheckboxGroup {
        /**
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * Consolidated web-component to show Open Data Hub data imported within the Digiway project
     */
    interface NoiDigiway {
        /**
          * Base map layer
          * @default 'tirol'
         */
        "baseMap"?: 'osm' | 'tirol';
        /**
          * Pass latitude, longitude and zoomlevel separated by "," if map should be centered an a specific gps point
         */
        "centermap"?: string;
        /**
          * Language
          * @default 'en'
         */
        "language"?: string;
        /**
          * Layout appearance
          * @default 'auto'
         */
        "layout"?: ViewLayout;
        /**
          * View date for weather data (weather layer only)
         */
        "viewDate"?: string | undefined;
    }
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiIcon {
        /**
          * icon name
         */
        "name"?: IconName | string;
    }
    /**
     * (INTERNAL) render a basic map with no layouts
     */
    interface NoiMap {
        /**
          * Map center. Pass latitude, longitude and zoomlevel separated by "," if map should be centered an a specific gps point
         */
        "centermap"?: string;
        /**
          * Emitted when map is initialized and ready to draw on it
         */
        "onMapReady"?: (event: NoiMapCustomEvent<Map>) => void;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapBaseCarto {
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapBaseOsm {
        /**
          * @default 'color'
         */
        "variant"?: 'color' | 'grayscale';
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapBaseTirol {
        /**
          * @default 'color'
         */
        "variant"?: 'color' | 'grayscale';
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerAnnouncements {
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerAnnouncementsCustomEvent<boolean>) => void;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerBaseOdh {
        "config": LayerConfig;
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerBaseOdhCustomEvent<boolean>) => void;
        "popupStructure"?: PopupDefinitionFn;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtp {
        "layers"?: string | string[];
        "layout"?: ViewLayout;
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerOtpCustomEvent<boolean>) => void;
        "onZoomCategoryChange"?: (event: NoiMapLayerOtpCustomEvent<ZoomCategory>) => void;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtpCharger {
        "onFeatureClick"?: (event: NoiMapLayerOtpChargerCustomEvent<MapGeoJSONFeature>) => void;
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerOtpChargerCustomEvent<boolean>) => void;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtpIcons {
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtpParking {
        "onFeatureClick"?: (event: NoiMapLayerOtpParkingCustomEvent<MapGeoJSONFeature>) => void;
    }
    /**
     * (INTERNAL) render otp popup
     */
    interface NoiMapLayerOtpPopupParking {
        /**
          * Emitted when user clicks on the route
         */
        "onRouteClick"?: (event: NoiMapLayerOtpPopupParkingCustomEvent<OtpTrip>) => void;
    }
    /**
     * (INTERNAL) render otp popup
     */
    interface NoiMapLayerOtpPopupStop {
        /**
          * Emitted when user clicks on the route
         */
        "onRouteClick"?: (event: NoiMapLayerOtpPopupStopCustomEvent<OtpStoptime>) => void;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtpRental {
        "onFeatureClick"?: (event: NoiMapLayerOtpRentalCustomEvent<MapGeoJSONFeature>) => void;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtpSource {
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerOtpSourceCustomEvent<boolean>) => void;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerOtpStops {
        "onFeatureClick"?: (event: NoiMapLayerOtpStopsCustomEvent<MapGeoJSONFeature>) => void;
    }
    /**
     * (INTERNAL)
     */
    interface NoiMapLayerOtpTrip {
        "layout"?: ViewLayout;
        "onClose"?: (event: NoiMapLayerOtpTripCustomEvent<'back' | 'close'>) => void;
        /**
          * Optional
         */
        "stopId"?: string;
        /**
          * Required
         */
        "tripId"?: string;
        "vehicleTypeOverride"?: string;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerPoi {
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerPoiCustomEvent<boolean>) => void;
        /**
          * View date for weather data
         */
        "tag"?: string;
    }
    /**
     * (INTERNAL) render map popup
     */
    interface NoiMapLayerPoiAccommodationPopup {
    }
    /**
     * (INTERNAL) render map popup
     */
    interface NoiMapLayerPoiPopup {
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerRiskExposure {
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerRiskExposureCustomEvent<boolean>) => void;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerRoads {
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerRoadsCustomEvent<boolean>) => void;
        "region": 'tyrol'
    | 'tyrol-north'
    | 'bolzano-int'
    | 'trento'
    | 'mountain-bike-bolzano'
    | 'mountain-bike-trento'
    | 'hiking-bolzano'
    | 'hiking-trento'
    | 'hiking-e5'
    | 'hiking-accessible';
        "titleIcon"?: string;
        "titleText"?: string;
    }
    /**
     * (INTERNAL) render map popup
     */
    interface NoiMapLayerRoadsPopup {
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerWeather {
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerWeatherCustomEvent<boolean>) => void;
        /**
          * View date for weather data
         */
        "viewDate"?: Date | undefined;
    }
    /**
     * (INTERNAL) render map layer
     */
    interface NoiMapLayerWeatherCurrent {
        /**
          * Emitted when layer data is loading
         */
        "onLayerLoading"?: (event: NoiMapLayerWeatherCurrentCustomEvent<boolean>) => void;
        /**
          * View date for weather data
          * @default 'temperature'
         */
        "viewMode"?: WeatherCurrentViewMode;
    }
    /**
     * (INTERNAL) render map popup
     */
    interface NoiMapLayerWeatherPopup {
    }
    interface NoiOtpDepartureTime {
        /**
          * @default true
         */
        "showDelay"?: boolean;
        "stoptime"?: OtpStoptime;
    }
    /**
     * (INTERNAL) render a select box
     */
    interface NoiSelect {
        /**
          * button 'disabled' property
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Emitted when user clicks on the button
         */
        "onSelectChange"?: (event: NoiSelectCustomEvent<string>) => void;
        "options"?: SelectOption[];
        /**
          * @default null
         */
        "value"?: string;
    }
    /**
     * (INTERNAL) render a apinner.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiSpinner {
    }
    /**
     * (INTERNAL) render stars.
     */
    interface NoiStars {
        /**
          * @default 0
         */
        "stars"?: number;
        /**
          * @default 5
         */
        "total"?: number;
    }

    interface NoiButtonAttributes {
        "disabled": boolean;
        "iconOnly": boolean;
    }
    interface NoiCheckboxAttributes {
        "disabled": boolean;
        "checked": boolean;
        "kind": 'checkbox' | 'chevron';
        "loading": boolean;
    }
    interface NoiCheckboxGroupAttributes {
        "open": boolean;
    }
    interface NoiDigiwayAttributes {
        "layout": ViewLayout;
        "baseMap": 'osm' | 'tirol';
        "centermap": string;
        "language": string;
        "viewDate": string | undefined;
    }
    interface NoiIconAttributes {
        "name": IconName | string;
    }
    interface NoiMapAttributes {
        "centermap": string;
    }
    interface NoiMapBaseOsmAttributes {
        "variant": 'color' | 'grayscale';
    }
    interface NoiMapBaseTirolAttributes {
        "variant": 'color' | 'grayscale';
    }
    interface NoiMapLayerOtpAttributes {
        "layers": string | string[];
        "layout": ViewLayout;
    }
    interface NoiMapLayerOtpTripAttributes {
        "tripId": string;
        "layout": ViewLayout;
        "stopId": string;
        "vehicleTypeOverride": string;
    }
    interface NoiMapLayerPoiAttributes {
        "tag": string;
    }
    interface NoiMapLayerRoadsAttributes {
        "region": 'tyrol'
    | 'tyrol-north'
    | 'bolzano-int'
    | 'trento'
    | 'mountain-bike-bolzano'
    | 'mountain-bike-trento'
    | 'hiking-bolzano'
    | 'hiking-trento'
    | 'hiking-e5'
    | 'hiking-accessible';
        "titleText": string;
        "titleIcon": string;
    }
    interface NoiMapLayerWeatherCurrentAttributes {
        "viewMode": WeatherCurrentViewMode;
    }
    interface NoiOtpDepartureTimeAttributes {
        "showDelay": boolean;
    }
    interface NoiSelectAttributes {
        "disabled": boolean;
        "value": string;
    }
    interface NoiStarsAttributes {
        "stars": number;
        "total": number;
    }

    interface IntrinsicElements {
        "noi-badge": NoiBadge;
        "noi-button": Omit<NoiButton, keyof NoiButtonAttributes> & { [K in keyof NoiButton & keyof NoiButtonAttributes]?: NoiButton[K] } & { [K in keyof NoiButton & keyof NoiButtonAttributes as `attr:${K}`]?: NoiButtonAttributes[K] } & { [K in keyof NoiButton & keyof NoiButtonAttributes as `prop:${K}`]?: NoiButton[K] };
        "noi-checkbox": Omit<NoiCheckbox, keyof NoiCheckboxAttributes> & { [K in keyof NoiCheckbox & keyof NoiCheckboxAttributes]?: NoiCheckbox[K] } & { [K in keyof NoiCheckbox & keyof NoiCheckboxAttributes as `attr:${K}`]?: NoiCheckboxAttributes[K] } & { [K in keyof NoiCheckbox & keyof NoiCheckboxAttributes as `prop:${K}`]?: NoiCheckbox[K] };
        "noi-checkbox-group": Omit<NoiCheckboxGroup, keyof NoiCheckboxGroupAttributes> & { [K in keyof NoiCheckboxGroup & keyof NoiCheckboxGroupAttributes]?: NoiCheckboxGroup[K] } & { [K in keyof NoiCheckboxGroup & keyof NoiCheckboxGroupAttributes as `attr:${K}`]?: NoiCheckboxGroupAttributes[K] } & { [K in keyof NoiCheckboxGroup & keyof NoiCheckboxGroupAttributes as `prop:${K}`]?: NoiCheckboxGroup[K] };
        "noi-digiway": Omit<NoiDigiway, keyof NoiDigiwayAttributes> & { [K in keyof NoiDigiway & keyof NoiDigiwayAttributes]?: NoiDigiway[K] } & { [K in keyof NoiDigiway & keyof NoiDigiwayAttributes as `attr:${K}`]?: NoiDigiwayAttributes[K] } & { [K in keyof NoiDigiway & keyof NoiDigiwayAttributes as `prop:${K}`]?: NoiDigiway[K] };
        "noi-icon": Omit<NoiIcon, keyof NoiIconAttributes> & { [K in keyof NoiIcon & keyof NoiIconAttributes]?: NoiIcon[K] } & { [K in keyof NoiIcon & keyof NoiIconAttributes as `attr:${K}`]?: NoiIconAttributes[K] } & { [K in keyof NoiIcon & keyof NoiIconAttributes as `prop:${K}`]?: NoiIcon[K] };
        "noi-map": Omit<NoiMap, keyof NoiMapAttributes> & { [K in keyof NoiMap & keyof NoiMapAttributes]?: NoiMap[K] } & { [K in keyof NoiMap & keyof NoiMapAttributes as `attr:${K}`]?: NoiMapAttributes[K] } & { [K in keyof NoiMap & keyof NoiMapAttributes as `prop:${K}`]?: NoiMap[K] };
        "noi-map-base-carto": NoiMapBaseCarto;
        "noi-map-base-osm": Omit<NoiMapBaseOsm, keyof NoiMapBaseOsmAttributes> & { [K in keyof NoiMapBaseOsm & keyof NoiMapBaseOsmAttributes]?: NoiMapBaseOsm[K] } & { [K in keyof NoiMapBaseOsm & keyof NoiMapBaseOsmAttributes as `attr:${K}`]?: NoiMapBaseOsmAttributes[K] } & { [K in keyof NoiMapBaseOsm & keyof NoiMapBaseOsmAttributes as `prop:${K}`]?: NoiMapBaseOsm[K] };
        "noi-map-base-tirol": Omit<NoiMapBaseTirol, keyof NoiMapBaseTirolAttributes> & { [K in keyof NoiMapBaseTirol & keyof NoiMapBaseTirolAttributes]?: NoiMapBaseTirol[K] } & { [K in keyof NoiMapBaseTirol & keyof NoiMapBaseTirolAttributes as `attr:${K}`]?: NoiMapBaseTirolAttributes[K] } & { [K in keyof NoiMapBaseTirol & keyof NoiMapBaseTirolAttributes as `prop:${K}`]?: NoiMapBaseTirol[K] };
        "noi-map-layer-announcements": NoiMapLayerAnnouncements;
        "noi-map-layer-base-odh": NoiMapLayerBaseOdh;
        "noi-map-layer-otp": Omit<NoiMapLayerOtp, keyof NoiMapLayerOtpAttributes> & { [K in keyof NoiMapLayerOtp & keyof NoiMapLayerOtpAttributes]?: NoiMapLayerOtp[K] } & { [K in keyof NoiMapLayerOtp & keyof NoiMapLayerOtpAttributes as `attr:${K}`]?: NoiMapLayerOtpAttributes[K] } & { [K in keyof NoiMapLayerOtp & keyof NoiMapLayerOtpAttributes as `prop:${K}`]?: NoiMapLayerOtp[K] };
        "noi-map-layer-otp-charger": NoiMapLayerOtpCharger;
        "noi-map-layer-otp-icons": NoiMapLayerOtpIcons;
        "noi-map-layer-otp-parking": NoiMapLayerOtpParking;
        "noi-map-layer-otp-popup-parking": NoiMapLayerOtpPopupParking;
        "noi-map-layer-otp-popup-stop": NoiMapLayerOtpPopupStop;
        "noi-map-layer-otp-rental": NoiMapLayerOtpRental;
        "noi-map-layer-otp-source": NoiMapLayerOtpSource;
        "noi-map-layer-otp-stops": NoiMapLayerOtpStops;
        "noi-map-layer-otp-trip": Omit<NoiMapLayerOtpTrip, keyof NoiMapLayerOtpTripAttributes> & { [K in keyof NoiMapLayerOtpTrip & keyof NoiMapLayerOtpTripAttributes]?: NoiMapLayerOtpTrip[K] } & { [K in keyof NoiMapLayerOtpTrip & keyof NoiMapLayerOtpTripAttributes as `attr:${K}`]?: NoiMapLayerOtpTripAttributes[K] } & { [K in keyof NoiMapLayerOtpTrip & keyof NoiMapLayerOtpTripAttributes as `prop:${K}`]?: NoiMapLayerOtpTrip[K] };
        "noi-map-layer-poi": Omit<NoiMapLayerPoi, keyof NoiMapLayerPoiAttributes> & { [K in keyof NoiMapLayerPoi & keyof NoiMapLayerPoiAttributes]?: NoiMapLayerPoi[K] } & { [K in keyof NoiMapLayerPoi & keyof NoiMapLayerPoiAttributes as `attr:${K}`]?: NoiMapLayerPoiAttributes[K] } & { [K in keyof NoiMapLayerPoi & keyof NoiMapLayerPoiAttributes as `prop:${K}`]?: NoiMapLayerPoi[K] };
        "noi-map-layer-poi-accommodation-popup": NoiMapLayerPoiAccommodationPopup;
        "noi-map-layer-poi-popup": NoiMapLayerPoiPopup;
        "noi-map-layer-risk-exposure": NoiMapLayerRiskExposure;
        "noi-map-layer-roads": Omit<NoiMapLayerRoads, keyof NoiMapLayerRoadsAttributes> & { [K in keyof NoiMapLayerRoads & keyof NoiMapLayerRoadsAttributes]?: NoiMapLayerRoads[K] } & { [K in keyof NoiMapLayerRoads & keyof NoiMapLayerRoadsAttributes as `attr:${K}`]?: NoiMapLayerRoadsAttributes[K] } & { [K in keyof NoiMapLayerRoads & keyof NoiMapLayerRoadsAttributes as `prop:${K}`]?: NoiMapLayerRoads[K] } & OneOf<"region", NoiMapLayerRoads["region"], NoiMapLayerRoadsAttributes["region"]>;
        "noi-map-layer-roads-popup": NoiMapLayerRoadsPopup;
        "noi-map-layer-weather": NoiMapLayerWeather;
        "noi-map-layer-weather-current": Omit<NoiMapLayerWeatherCurrent, keyof NoiMapLayerWeatherCurrentAttributes> & { [K in keyof NoiMapLayerWeatherCurrent & keyof NoiMapLayerWeatherCurrentAttributes]?: NoiMapLayerWeatherCurrent[K] } & { [K in keyof NoiMapLayerWeatherCurrent & keyof NoiMapLayerWeatherCurrentAttributes as `attr:${K}`]?: NoiMapLayerWeatherCurrentAttributes[K] } & { [K in keyof NoiMapLayerWeatherCurrent & keyof NoiMapLayerWeatherCurrentAttributes as `prop:${K}`]?: NoiMapLayerWeatherCurrent[K] };
        "noi-map-layer-weather-popup": NoiMapLayerWeatherPopup;
        "noi-otp-departure-time": Omit<NoiOtpDepartureTime, keyof NoiOtpDepartureTimeAttributes> & { [K in keyof NoiOtpDepartureTime & keyof NoiOtpDepartureTimeAttributes]?: NoiOtpDepartureTime[K] } & { [K in keyof NoiOtpDepartureTime & keyof NoiOtpDepartureTimeAttributes as `attr:${K}`]?: NoiOtpDepartureTimeAttributes[K] } & { [K in keyof NoiOtpDepartureTime & keyof NoiOtpDepartureTimeAttributes as `prop:${K}`]?: NoiOtpDepartureTime[K] };
        "noi-select": Omit<NoiSelect, keyof NoiSelectAttributes> & { [K in keyof NoiSelect & keyof NoiSelectAttributes]?: NoiSelect[K] } & { [K in keyof NoiSelect & keyof NoiSelectAttributes as `attr:${K}`]?: NoiSelectAttributes[K] } & { [K in keyof NoiSelect & keyof NoiSelectAttributes as `prop:${K}`]?: NoiSelect[K] };
        "noi-spinner": NoiSpinner;
        "noi-stars": Omit<NoiStars, keyof NoiStarsAttributes> & { [K in keyof NoiStars & keyof NoiStarsAttributes]?: NoiStars[K] } & { [K in keyof NoiStars & keyof NoiStarsAttributes as `attr:${K}`]?: NoiStarsAttributes[K] } & { [K in keyof NoiStars & keyof NoiStarsAttributes as `prop:${K}`]?: NoiStars[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * (INTERNAL) render a badge.
             */
            "noi-badge": LocalJSX.IntrinsicElements["noi-badge"] & JSXBase.HTMLAttributes<HTMLNoiBadgeElement>;
            /**
             * (INTERNAL) Backdrop component.
             */
            "noi-button": LocalJSX.IntrinsicElements["noi-button"] & JSXBase.HTMLAttributes<HTMLNoiButtonElement>;
            /**
             * (INTERNAL) render a checkbox
             */
            "noi-checkbox": LocalJSX.IntrinsicElements["noi-checkbox"] & JSXBase.HTMLAttributes<HTMLNoiCheckboxElement>;
            /**
             * (INTERNAL) render a checkbox group
             */
            "noi-checkbox-group": LocalJSX.IntrinsicElements["noi-checkbox-group"] & JSXBase.HTMLAttributes<HTMLNoiCheckboxGroupElement>;
            /**
             * Consolidated web-component to show Open Data Hub data imported within the Digiway project
             */
            "noi-digiway": LocalJSX.IntrinsicElements["noi-digiway"] & JSXBase.HTMLAttributes<HTMLNoiDigiwayElement>;
            /**
             * (INTERNAL) render an icon.
             * Icons are embedded inside the component (so far).
             * Icon size can be changed by 'font-size' style
             */
            "noi-icon": LocalJSX.IntrinsicElements["noi-icon"] & JSXBase.HTMLAttributes<HTMLNoiIconElement>;
            /**
             * (INTERNAL) render a basic map with no layouts
             */
            "noi-map": LocalJSX.IntrinsicElements["noi-map"] & JSXBase.HTMLAttributes<HTMLNoiMapElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-base-carto": LocalJSX.IntrinsicElements["noi-map-base-carto"] & JSXBase.HTMLAttributes<HTMLNoiMapBaseCartoElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-base-osm": LocalJSX.IntrinsicElements["noi-map-base-osm"] & JSXBase.HTMLAttributes<HTMLNoiMapBaseOsmElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-base-tirol": LocalJSX.IntrinsicElements["noi-map-base-tirol"] & JSXBase.HTMLAttributes<HTMLNoiMapBaseTirolElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-announcements": LocalJSX.IntrinsicElements["noi-map-layer-announcements"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerAnnouncementsElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-base-odh": LocalJSX.IntrinsicElements["noi-map-layer-base-odh"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerBaseOdhElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-otp": LocalJSX.IntrinsicElements["noi-map-layer-otp"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerOtpElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-otp-charger": LocalJSX.IntrinsicElements["noi-map-layer-otp-charger"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerOtpChargerElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-otp-icons": LocalJSX.IntrinsicElements["noi-map-layer-otp-icons"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerOtpIconsElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-otp-parking": LocalJSX.IntrinsicElements["noi-map-layer-otp-parking"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerOtpParkingElement>;
            /**
             * (INTERNAL) render otp popup
             */
            "noi-map-layer-otp-popup-parking": LocalJSX.IntrinsicElements["noi-map-layer-otp-popup-parking"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerOtpPopupParkingElement>;
            /**
             * (INTERNAL) render otp popup
             */
            "noi-map-layer-otp-popup-stop": LocalJSX.IntrinsicElements["noi-map-layer-otp-popup-stop"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerOtpPopupStopElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-otp-rental": LocalJSX.IntrinsicElements["noi-map-layer-otp-rental"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerOtpRentalElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-otp-source": LocalJSX.IntrinsicElements["noi-map-layer-otp-source"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerOtpSourceElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-otp-stops": LocalJSX.IntrinsicElements["noi-map-layer-otp-stops"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerOtpStopsElement>;
            /**
             * (INTERNAL)
             */
            "noi-map-layer-otp-trip": LocalJSX.IntrinsicElements["noi-map-layer-otp-trip"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerOtpTripElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-poi": LocalJSX.IntrinsicElements["noi-map-layer-poi"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerPoiElement>;
            /**
             * (INTERNAL) render map popup
             */
            "noi-map-layer-poi-accommodation-popup": LocalJSX.IntrinsicElements["noi-map-layer-poi-accommodation-popup"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerPoiAccommodationPopupElement>;
            /**
             * (INTERNAL) render map popup
             */
            "noi-map-layer-poi-popup": LocalJSX.IntrinsicElements["noi-map-layer-poi-popup"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerPoiPopupElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-risk-exposure": LocalJSX.IntrinsicElements["noi-map-layer-risk-exposure"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerRiskExposureElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-roads": LocalJSX.IntrinsicElements["noi-map-layer-roads"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerRoadsElement>;
            /**
             * (INTERNAL) render map popup
             */
            "noi-map-layer-roads-popup": LocalJSX.IntrinsicElements["noi-map-layer-roads-popup"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerRoadsPopupElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-weather": LocalJSX.IntrinsicElements["noi-map-layer-weather"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerWeatherElement>;
            /**
             * (INTERNAL) render map layer
             */
            "noi-map-layer-weather-current": LocalJSX.IntrinsicElements["noi-map-layer-weather-current"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerWeatherCurrentElement>;
            /**
             * (INTERNAL) render map popup
             */
            "noi-map-layer-weather-popup": LocalJSX.IntrinsicElements["noi-map-layer-weather-popup"] & JSXBase.HTMLAttributes<HTMLNoiMapLayerWeatherPopupElement>;
            "noi-otp-departure-time": LocalJSX.IntrinsicElements["noi-otp-departure-time"] & JSXBase.HTMLAttributes<HTMLNoiOtpDepartureTimeElement>;
            /**
             * (INTERNAL) render a select box
             */
            "noi-select": LocalJSX.IntrinsicElements["noi-select"] & JSXBase.HTMLAttributes<HTMLNoiSelectElement>;
            /**
             * (INTERNAL) render a apinner.
             * Icons are embedded inside the component (so far).
             * Icon size can be changed by 'font-size' style
             */
            "noi-spinner": LocalJSX.IntrinsicElements["noi-spinner"] & JSXBase.HTMLAttributes<HTMLNoiSpinnerElement>;
            /**
             * (INTERNAL) render stars.
             */
            "noi-stars": LocalJSX.IntrinsicElements["noi-stars"] & JSXBase.HTMLAttributes<HTMLNoiStarsElement>;
        }
    }
}
